name: "✨ 功能建议"
description: 建议新功能或改进
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        感谢您使用 CodeStyle！请花些时间填写这份功能建议。
        
        **提示**：提交前请先搜索是否有类似的建议。

  - type: checkboxes
    id: checkboxes
    attributes:
      label: 确认事项
      options:
        - label: 我已搜索过 [Issues](https://github.com/codestyle-team/codestyle/issues)，没有类似的建议
          required: true
        - label: 我已阅读过 [README](https://github.com/codestyle-team/codestyle/blob/main/README.md)
          required: true
        - label: 我确认这是一个通用需求，而不是特定业务需求
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 清楚简洁地描述您的建议
      placeholder: 例如：希望支持 xxx 功能...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景
      description: 描述这个功能的使用场景
      placeholder: 在什么情况下需要这个功能？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您认为应该如何实现
      placeholder: 可以通过 xxx 方式实现...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过的其他方案
      placeholder: 也可以考虑 xxx 方式...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 其他有助于理解需求的信息（截图、链接等）
    validations:
      required: false
